services:

  api:
    image: datascientest/fastapi:1.0.0
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
  
  authorization_tests:
    image: authorization_tests:latest
    command: python3 test_authorization.py
    depends_on:
      - api
  
  authentication_tests:
    image: authentication_tests:latest
    command: python3 test_authentication.py
    depends_on:
      - api
  
  content_tests:
    image: content_tests:latest
    command: python3 test_content.py
    depends_on:
      - api

networks:
  test_net: