services:

  api:
    image: datascientest/fastapi:1.0.0
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
  
  authorization_tests:
    build: ./tests/authorization
    command: python3 test_authorization.py
    volumes:
      - ${HOME}/exam_docker_ALONSO_LANZA/sentiment_api/api_test.log:/api_test.log 
    environment:
      - HOST=api
      - LOG=1
    depends_on:
      - api


  authentication_tests:
    build: ./tests/authentication
    command: python3 test_authentication.py
    environment:
      - HOST=api
      - LOG=1
    volumes:
      - ${HOME}/exam_docker_ALONSO_LANZA/sentiment_api/api_test.log:/api_test.log
    depends_on:
      - api
  
  content_tests:
    build: ./tests/content
    command: python3 test_content.py
    environment:
      - HOST=api
      - LOG=1
    volumes:
      - ${HOME}/exam_docker_ALONSO_LANZA/sentiment_api/api_test.log:/api_test.log
    depends_on:
      - api
